version : '3'
services : 
  sql : 
    image : mariadb
    ports : 
      - "3307:3306"
    environment :
      MYSQL_ROOT_PASSWORD : root
    volumes :
      - ./databaseConfig:/docker-entrypoint-initdb.d
      - ./databaseData:/var/lib/mysql/
  nginx :
    build :
      context: './docker-base'
    ports :
      - "80:80"
    depends_on :
      - sql
    volumes :
      - ./code:/srv/www
      - ./logs:/LOGS